# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-09 09:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authnz', '0002_auto_20151209_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proqoduser',
            name='username',
        ),
    ]
