# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-10 08:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_batch', models.CharField(blank=True, help_text='Identify the batch of the course e.g. FY15T3 for Year 2015 Term 3', max_length=20, verbose_name='course batch')),
                ('course_code', models.CharField(blank=True, help_text='e.g. CS101', max_length=20, verbose_name='course code')),
                ('school', models.CharField(blank=True, help_text='e.g. SUTD', max_length=100, null=True)),
                ('department', models.CharField(blank=True, help_text='e.g. ISTD', max_length=100, null=True)),
                ('title', models.CharField(blank=True, help_text='e.g. Digital World', max_length=50, null=True)),
                ('description', models.TextField(blank=True, help_text='e.g. An introduction course to programming using Python', max_length=255, null=True)),
                ('programming_language', models.CharField(help_text='e.g. Python', max_length=55, verbose_name='programming language')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(verbose_name='end date')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('participants', models.ManyToManyField(related_name='courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_created'],
                'verbose_name': 'course',
                'verbose_name_plural': 'courses',
            },
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together=set([('course_batch', 'course_code', 'school', 'department')]),
        ),
    ]
