# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 16:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MultipleChoices',
            new_name='MultipleChoice',
        ),
        migrations.AlterModelOptions(
            name='blankquestioncontent',
            options={'ordering': ['question'], 'verbose_name': 'blank_question_part', 'verbose_name_plural': 'blank_question_parts'},
        ),
        migrations.AlterModelOptions(
            name='multiplechoice',
            options={'ordering': ['question'], 'verbose_name': 'multiple_choice', 'verbose_name_plural': 'multiple_choices'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['assessment', 'question_num'], 'verbose_name': 'question', 'verbose_name_plural': 'questions'},
        ),
        migrations.AlterUniqueTogether(
            name='blankquestioncontent',
            unique_together=set([('seq', 'question')]),
        ),
        migrations.AlterUniqueTogether(
            name='multiplechoice',
            unique_together=set([('question',)]),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together=set([('assessment', 'question_num')]),
        ),
    ]
