# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-10 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_batch',
            field=models.CharField(blank=True, help_text='e.g. FY15T3 (for Year 2015 Term 3)', max_length=20, verbose_name='course batch'),
        ),
    ]
